"""add workflow executions table

Revision ID: 061d61090d8b
Revises: 56e5f85b55a8
Create Date: 2026-07-05 17:40:28.306183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '061d61090d8b'
down_revision: Union[str, Sequence[str], None] = '56e5f85b55a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_executions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.String(length=500), nullable=False),
    sa.Column('ticket_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('failure_stage', sa.String(length=100), nullable=True),
    sa.Column('error_type', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_metadata', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name='fk_workflow_execution_ticket', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.drop_index(op.f('idx_ticket_category'), table_name='tickets')
    op.drop_index(op.f('idx_ticket_email'), table_name='tickets')
    op.drop_index(op.f('idx_ticket_priority'), table_name='tickets')
    op.drop_index(op.f('idx_ticket_received'), table_name='tickets')
    op.drop_index(op.f('idx_ticket_status'), table_name='tickets')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_ticket_status'), 'tickets', ['status'], unique=False)
    op.create_index(op.f('idx_ticket_received'), 'tickets', ['received_at'], unique=False)
    op.create_index(op.f('idx_ticket_priority'), 'tickets', ['priority'], unique=False)
    op.create_index(op.f('idx_ticket_email'), 'tickets', ['sender_email'], unique=False)
    op.create_index(op.f('idx_ticket_category'), 'tickets', ['category'], unique=False)
    op.drop_table('workflow_executions')
    # ### end Alembic commands ###
