"""add workflow failure recovery and dead letters

Revision ID: 1e61e5586f96
Revises: 490a62ac39b2
Create Date: 2026-07-05 23:05:48.003992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e61e5586f96'
down_revision: Union[str, Sequence[str], None] = '490a62ac39b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dead_letter_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_execution_id', sa.BigInteger(), nullable=False),
    sa.Column('ticket_id', sa.BigInteger(), nullable=True),
    sa.Column('failed_stage', sa.String(length=100), nullable=False),
    sa.Column('exception_type', sa.String(length=255), nullable=False),
    sa.Column('sanitized_error_message', sa.Text(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('retry_exhausted', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('manual_retry_count', sa.Integer(), nullable=False),
    sa.Column('last_retry_execution_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['last_retry_execution_id'], ['workflow_executions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_execution_id'], ['workflow_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dead_letter_records_status'), 'dead_letter_records', ['status'], unique=False)
    op.create_index(op.f('ix_dead_letter_records_ticket_id'), 'dead_letter_records', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_dead_letter_records_workflow_execution_id'), 'dead_letter_records', ['workflow_execution_id'], unique=True)
    op.add_column('workflow_executions', sa.Column('retry_exhausted', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('workflow_executions', sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workflow_executions', sa.Column('parent_execution_id', sa.BigInteger(), nullable=True))
    op.add_column('workflow_executions', sa.Column('attempt_number', sa.Integer(), server_default='1', nullable=False))
    op.create_foreign_key('fk_workflow_execution_parent', 'workflow_executions', 'workflow_executions', ['parent_execution_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_workflow_execution_parent', 'workflow_executions', type_='foreignkey')
    op.drop_column('workflow_executions', 'attempt_number')
    op.drop_column('workflow_executions', 'parent_execution_id')
    op.drop_column('workflow_executions', 'failed_at')
    op.drop_column('workflow_executions', 'retry_exhausted')
    op.drop_index(op.f('ix_dead_letter_records_workflow_execution_id'), table_name='dead_letter_records')
    op.drop_index(op.f('ix_dead_letter_records_ticket_id'), table_name='dead_letter_records')
    op.drop_index(op.f('ix_dead_letter_records_status'), table_name='dead_letter_records')
    op.drop_table('dead_letter_records')
    # ### end Alembic commands ###
