"""extend workflow execution monitoring

Revision ID: 490a62ac39b2
Revises: add7816d9375
Create Date: 2026-07-05 21:28:59.401573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '490a62ac39b2'
down_revision: Union[str, Sequence[str], None] = 'add7816d9375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('acknowledgement_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workflow_executions', sa.Column('execution_id', sa.String(length=36), nullable=False))
    op.add_column('workflow_executions', sa.Column('duration_ms', sa.BigInteger(), nullable=True))
    op.add_column('workflow_executions', sa.Column('current_stage', sa.String(length=100), nullable=False))
    op.add_column('workflow_executions', sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('workflow_executions', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('workflow_executions', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('workflow_executions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index('ix_workflow_executions_execution_id', 'workflow_executions', ['execution_id'], unique=True)
    op.create_index('ix_workflow_executions_started_at', 'workflow_executions', ['started_at'], unique=False)
    op.create_index('ix_workflow_executions_status', 'workflow_executions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workflow_executions_status', table_name='workflow_executions')
    op.drop_index('ix_workflow_executions_started_at', table_name='workflow_executions')
    op.drop_index('ix_workflow_executions_execution_id', table_name='workflow_executions')
    op.alter_column('workflow_executions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('workflow_executions', 'completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('workflow_executions', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('workflow_executions', 'retry_count')
    op.drop_column('workflow_executions', 'current_stage')
    op.drop_column('workflow_executions', 'duration_ms')
    op.drop_column('workflow_executions', 'execution_id')
    op.drop_column('tickets', 'acknowledgement_sent_at')
    # ### end Alembic commands ###
