"""add dashboard ai fields to tickets

Revision ID: 523653755e66
Revises: c86ea2d4ec8f
Create Date: 2026-07-05 19:19:03.677004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '523653755e66'
down_revision: Union[str, Sequence[str], None] = 'c86ea2d4ec8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('priority_reason', sa.Text(), nullable=True))
    op.add_column('tickets', sa.Column('suggested_reply', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'suggested_reply')
    op.drop_column('tickets', 'priority_reason')
    # ### end Alembic commands ###
