"""allow workflow retry execution lineage

Revision ID: 7e612b8b54a2
Revises: 1e61e5586f96
Create Date: 2026-07-05 23:18:15.360727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e612b8b54a2'
down_revision: Union[str, Sequence[str], None] = '1e61e5586f96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('workflow_executions_message_id_key'), 'workflow_executions', type_='unique')
    op.create_index('ix_workflow_executions_message_id', 'workflow_executions', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workflow_executions_message_id', table_name='workflow_executions')
    op.create_unique_constraint(op.f('workflow_executions_message_id_key'), 'workflow_executions', ['message_id'])
    # ### end Alembic commands ###
