"""restore ticket indexes

Revision ID: c86ea2d4ec8f
Revises: 061d61090d8b
Create Date: 2026-07-05 17:45:26.599560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c86ea2d4ec8f'
down_revision: Union[str, Sequence[str], None] = '061d61090d8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    """Restore ticket indexes."""

    op.create_index(
        "idx_ticket_category",
        "tickets",
        ["category"],
        unique=False,
    )

    op.create_index(
        "idx_ticket_email",
        "tickets",
        ["sender_email"],
        unique=False,
    )

    op.create_index(
        "idx_ticket_priority",
        "tickets",
        ["priority"],
        unique=False,
    )

    op.create_index(
        "idx_ticket_received",
        "tickets",
        ["received_at"],
        unique=False,
    )

    op.create_index(
        "idx_ticket_status",
        "tickets",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    """Remove restored ticket indexes."""

    op.drop_index(
        "idx_ticket_status",
        table_name="tickets",
    )

    op.drop_index(
        "idx_ticket_received",
        table_name="tickets",
    )

    op.drop_index(
        "idx_ticket_priority",
        table_name="tickets",
    )

    op.drop_index(
        "idx_ticket_email",
        table_name="tickets",
    )

    op.drop_index(
        "idx_ticket_category",
        table_name="tickets",
    )
    # ### end Alembic commands ###
